### ISSUE TITLE
publishing msgs with composite collections doesn't seem to work

### ISSUE THREAD

**Issue by chadrockey** [rosjava/rosjava_core#112]
_Original author: drzaius...@gmail.com (May 10, 2012 22:34:36)_

<b>What steps will reproduce the problem?</b>
1. create a test package with an Inner and Outer msg def

Outter contains an array of Inner msgs
1. write a simple publish loop in rosjava:

protected void loop() throws InterruptedException {
            test_composite_msgs.Outer outter = node.getTopicMessageFactory().newFromType(test_composite_msgs.Outer._TYPE);//publisher.newMessage();
            outter.setInnerMsgs(new ArrayList&lt;test_composite_msgs.Inner&gt;());
            test_composite_msgs.Inner in = node.getTopicMessageFactory().newFromType(test_composite_msgs.Inner._TYPE);
            outter.getInnerMsgs().add(in);
            publisher.publish(outter);
            sequenceNumber++;
            Thread.sleep(1000);
        }
1. run in node runner (it crashes)

<b>What is the expected output? What do you see instead?</b>
get a casting error instead of anything publishing

<b>What version of the product are you using? On what operating system?</b>
e417224a6150, ubuntu 11.10

<b>Please provide any additional information below.</b>
see http://answers.ros.org/question/33742/how-to-add-collections-of-composite-messages-in

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=112_

**Comment by chadrockey** [comment]
_From drzaius...@gmail.com on May 11, 2012 11:02:24_
exception thrown:

Exception in thread "pool-1-thread-9" java.lang.ClassCastException: org.ros.internal.message.$Proxy2 cannot be cast to org.ros.internal.message.RawMessage
    at org.ros.internal.message.ListField.getSerializedSize(ListField.java:91)
    at org.ros.internal.message.MessageImpl.getSerializedSize(MessageImpl.java:450)
    at org.ros.internal.message.MessageImpl.serialize(MessageImpl.java:457)
    at org.ros.internal.message.DefaultMessageSerializer.serialize(DefaultMessageSerializer.java:30)
    at org.ros.internal.message.DefaultMessageSerializer.serialize(DefaultMessageSerializer.java:26)
    at org.ros.internal.transport.OutgoingMessageQueue.writeMessageToChannel(OutgoingMessageQueue.java:79)
    at org.ros.internal.transport.OutgoingMessageQueue.access$100(OutgoingMessageQueue.java:38)
    at org.ros.internal.transport.OutgoingMessageQueue$Writer.loop(OutgoingMessageQueue.java:56)
    at org.ros.concurrent.CancellableLoop.run(CancellableLoop.java:49)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:722)

**Comment by chadrockey** [comment]
_From damonkoh...@google.com on July 05, 2012 08:34:39_
I can't reproduce this. I assume it was fixed unintentionally at some point.
