### ISSUE TITLE
use_sim_time causes NPE

### ISSUE THREAD

**Issue by chadrockey** [rosjava/rosjava_core#115]
_Original author: damonkoh...@google.com (May 21, 2012 15:59:19)_

Bring up a node when use_sim_time is true and an NPE is thrown.

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=115_

**Comment by chadrockey** [comment]
_From wortmann...@gmail.com on May 29, 2012 10:10:57_
Removed rosjava directory, updated workspace, reinstalled, still doesn't work for me.  Given the setup [1] the new exception (which now is thrown continuously) is

Exception in thread "pool-1-thread-75" java.lang.NullPointerException
    at org.ros.time.ClockTopicTimeProvider$1.onNewMessage(ClockTopicTimeProvider.java:45)
    at org.ros.time.ClockTopicTimeProvider$1.onNewMessage(ClockTopicTimeProvider.java:42)
    at org.ros.internal.transport.IncomingMessageQueue$Dispatcher$1.run(IncomingMessageQueue.java:77)
    at org.ros.internal.transport.IncomingMessageQueue$Dispatcher$1.run(IncomingMessageQueue.java:74)
    at org.ros.concurrent.ListenerCollection$1.run(ListenerCollection.java:117)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)
Exception in thread "pool-1-thread-85" java.lang.NullPointerException
    at org.ros.time.ClockTopicTimeProvider$1.onNewMessage(ClockTopicTimeProvider.java:45)
    at org.ros.time.ClockTopicTimeProvider$1.onNewMessage(ClockTopicTimeProvider.java:42)
    at org.ros.internal.transport.IncomingMessageQueue$Dispatcher$1.run(IncomingMessageQueue.java:77)
    at org.ros.internal.transport.IncomingMessageQueue$Dispatcher$1.run(IncomingMessageQueue.java:74)
    at org.ros.concurrent.ListenerCollection$1.run(ListenerCollection.java:117)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)

[1] http://answers.ros.org/question/34373/rosjava-gazebo-problem-with-sim-time/

**Comment by chadrockey** [comment]
_From mate.wol...@gmail.com on July 02, 2012 11:16:58_
In ClockTopicTimeProvider, before assigning any value to the field rosgraph_msgs.Clock clock, a synchronize is attempted on the very same field, which is null at that point. (code checked out June 28th)

As a quick fix, add a separate object that is anything but null and use that for synchronization.
