### ISSUE TITLE
IndexOutOfBoundsException: Not enough readable bytes

### ISSUE THREAD

**Issue by chadrockey** [rosjava/rosjava_core#126]
_Original author: mate.wol...@gmail.com (July 04, 2012 11:25:40)_

Keep getting the following exception after rosjava update on June 28th:

Exception in thread &quot;pool-1-thread-29&quot; java.lang.IndexOutOfBoundsException: Not enough readable bytes - Need 4, maximum is 0
        at org.jboss.netty.buffer.AbstractChannelBuffer.checkReadableBytes(AbstractChannelBuffer.java:661)
        at org.jboss.netty.buffer.AbstractChannelBuffer.readInt(AbstractChannelBuffer.java:273)
        at org.ros.internal.message.field.PrimitiveFieldType$8.deserialize(PrimitiveFieldType.java:342)
        at org.ros.internal.message.field.PrimitiveFieldType$8.deserialize(PrimitiveFieldType.java:316)
        at org.ros.internal.message.field.PrimitiveFieldType$9.deserialize(PrimitiveFieldType.java:381)
        at org.ros.internal.message.field.PrimitiveFieldType$9.deserialize(PrimitiveFieldType.java:356)
        at org.ros.internal.message.field.ValueField.deserialize(ValueField.java:68)
        at org.ros.internal.message.DefaultMessageDeserializer.deserialize(DefaultMessageDeserializer.java:45)
        at org.ros.internal.message.field.MessageFieldType.deserialize(MessageFieldType.java:98)
        at org.ros.internal.message.field.MessageFieldType.deserialize(MessageFieldType.java:32)
        at org.ros.internal.message.field.ValueField.deserialize(ValueField.java:68)
        at org.ros.internal.message.DefaultMessageDeserializer.deserialize(DefaultMessageDeserializer.java:45)
        at org.ros.internal.message.field.MessageFieldType.deserialize(MessageFieldType.java:98)
        at org.ros.internal.message.field.MessageFieldType.deserialize(MessageFieldType.java:32)
        at org.ros.internal.message.field.ListField.deserialize(ListField.java:71)
        at org.ros.internal.message.DefaultMessageDeserializer.deserialize(DefaultMessageDeserializer.java:45)
        at org.ros.internal.message.field.MessageFieldType.deserialize(MessageFieldType.java:98)
        at org.ros.internal.message.field.MessageFieldType.deserialize(MessageFieldType.java:32)
        at org.ros.internal.message.field.ListField.deserialize(ListField.java:71)
        at org.ros.internal.message.DefaultMessageDeserializer.deserialize(DefaultMessageDeserializer.java:45)
        at org.ros.internal.transport.IncomingMessageQueue$Dispatcher.loop(IncomingMessageQueue.java:78)
        at org.ros.concurrent.CancellableLoop.run(CancellableLoop.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:679)

<b>What version of the product are you using? On what operating system?</b>
Head revision, June 28th 2012
Rosjava running in a pure Windows 7 environment.

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=126_

**Comment by kjitender469** [comment]
Hello @chadrockey. I am facing the same issue. Is someone resolves this issue?
