### ISSUE TITLE
Support wild cards in handshake headers

### ISSUE THREAD

**Issue by chadrockey** [rosjava/rosjava_core#13]
_Original author: ada...@gmail.com (June 16, 2011 23:53:21)_

<b>What steps will reproduce the problem?</b>
1. run the Talker node from the rosjava tutorial
2. run &quot;rostopic hz chatter&quot;
<b>3.</b>

<b>What is the expected output? What do you see instead?</b>
This causes a big exception to occur in the Talker node:
Loading node class: org.ros.tutorials.pubsub.Talker
Jun 16, 2011 4:50:35 PM org.jboss.netty.channel.DefaultChannelPipeline
WARNING: An exception was thrown by a user handler while handling an exception event ([id: 0x4090c06f, /127.0.0.1:49358 :&gt; /127.0.0.1:36547] EXCEPTION: java.lang.IllegalStateException)
java.lang.RuntimeException: java.lang.IllegalStateException
    at org.ros.internal.transport.ConnectionTrackingHandler.exceptionCaught(ConnectionTrackingHandler.java:62)
    at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:432)
    at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:52)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:317)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:299)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:216)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)
    at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:636)
Caused by: java.lang.IllegalStateException
    at com.google.common.base.Preconditions.checkState(Preconditions.java:129)
    at org.ros.internal.node.topic.Publisher.finishHandshake(Publisher.java:85)
    at org.ros.internal.transport.tcp.TcpServerHandshakeHandler.messageReceived(TcpServerHandshakeHandler.java:80)
    ... 12 more

Rostopic hz reports:
rostopic hz chatter
subscribed to [/chatter]

<b>What version of the product are you using? On what operating system?</b>
Latest repo of rosjava and Ubuntu operating system.

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=13_

**Comment by chadrockey** [comment]
_From damonkoh...@google.com on June 29, 2011 15:23:55_
This is happening because rosjava does not allow specifying md5sum=\* or type=\* in the handshake.

**Comment by chadrockey** [comment]
_From moese...@google.com on October 18, 2011 13:51:14_
This has been fixed in revision ca6ecfeba48b. I think the ticket can be closed.
