### ISSUE TITLE
NullPointerException in logger when called before first clock message

### ISSUE THREAD

**Issue by chadrockey** [rosjava/rosjava_core#148]
_Original author: martin.g...@gmail.com (October 28, 2012 13:26:11)_

<b>What steps will reproduce the problem?</b>
1. Start a roscore with param use_sim_time=true, but don't publish /clock yet (i.e., no rosbag play, no gazebo)
2. Create a new node that does something in onStart() which will directly or indirectly trigger connectedNode.getCurrentTime(), such as connectedNode.getLog().fatal(e)

<b>What is the expected output? What do you see instead?</b>

Exception in thread &quot;pool-1-thread-3&quot; java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:191)
    at org.ros.time.ClockTopicTimeProvider.getCurrentTime(ClockTopicTimeProvider.java:60)
    at org.ros.internal.node.DefaultNode.getCurrentTime(DefaultNode.java:377)
    at org.ros.internal.node.RosoutLogger.publish(RosoutLogger.java:58)
    at org.ros.internal.node.RosoutLogger.fatal(RosoutLogger.java:182)
    at race_sam_reasoner.RaceSamNode.onStart(RaceSamNode.java:127)
    at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:506)
    at org.ros.internal.node.DefaultNode$5.run(DefaultNode.java:503)
    at org.ros.concurrent.EventDispatcher.loop(EventDispatcher.java:43)
    at org.ros.concurrent.CancellableLoop.run(CancellableLoop.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
    at java.lang.Thread.run(Thread.java:679)

<b>What version of the product are you using? On what operating system?</b>

rosjava -r 1096:c655a7f4f79a, Ubuntu Oneiric 11.10, ROS fuerte

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=148_

**Comment by chadrockey** [comment]
_From martin.g...@gmail.com on October 28, 2012 13:31:16_
For an ugly workaround, add the following as the first lines of onStart():

// wait until we have a clock signal
while (true) {
    try {
        connectedNode.getCurrentTime();
        break; // no exception, so let's stop waiting
    } catch (NullPointerException e) {
        try {
            Thread.sleep(100);
        } catch (InterruptedException e1) {
        }
    }
}

**Comment by drigz** [comment]
Fixed by #264.

**Comment by mintar** [comment]
Nice! I forgot that I had even submitted this issue five and a half years ago, until I got the notification email that it's fixed now. Thanks @drigz ! :)
