### ISSUE TITLE
Create a new node through DefaultNodeFactory

### ISSUE THREAD

**Issue by ikalkov** [rosjava/rosjava_core#210]
Calling `newNode(nodeConfiguration)` Method in `DefaultNodeFactory` class leads to a NPE:

Exception in thread "main" java.lang.NullPointerException
    at org.ros.concurrent.ListenerGroup.addAll(ListenerGroup.java:85)
    at org.ros.concurrent.ListenerGroup.addAll(ListenerGroup.java:101)
    at org.ros.internal.node.DefaultNode.<init>(DefaultNode.java:132)
    at org.ros.node.DefaultNodeFactory.newNode(DefaultNodeFactory.java:43)
    at org.ros.node.DefaultNodeFactory.newNode(DefaultNodeFactory.java:48)

Perhaps it would be a better idea call the constructor using an empty collection, instead of null.

**Comment by ikalkov** [comment]
Seems to be dead. We switched to another project.
