### ISSUE TITLE
Removal of actionlib goal handles is not synchronized.

### ISSUE THREAD

**Issue by chadrockey** [rosjava/rosjava_core#31]
_Original author: psi...@gmail.com (September 02, 2011 04:36:25)_

<b>What steps will reproduce the problem?</b>
1. Run a SimpleActionServer.
2. Submit a whole lot of actions in quick succession.
3. Wait for a concurrent modification of GoalHandles to occur.

<b>What is the expected output? What do you see instead?</b>

Exception in thread &quot;Thread-38&quot; java.util.ConcurrentModificationException\
    at java.util.AbstractList$Itr.checkForComodification(AbstractList.java:372)\
    at java.util.AbstractList$Itr.next(AbstractList.java:343)\
    at org.ros.actionlib.client.GoalManager.updateFeedbacks(GoalManager.java:178)\
    at org.ros.actionlib.client.ActionClient.doFeedbackCallback(ActionClient.java:514)\
    at org.ros.actionlib.client.ActionClient$1.onNewMessage(ActionClient.java:198)\
    at org.ros.actionlib.client.ActionClient$1.onNewMessage(ActionClient.java:195)\

<b>What version of the product are you using? On what operating system?</b>

Latest trunk version of rosjava/actionlib.

<b>Please provide any additional information below.</b>

org.ros.actionlib.client.GoalManager is missing synchronized() blocks to guard access to listOfGoalHandles in the deleteGoalHandle(s) functions.  Eventually, this causes listOfGoalHandles to be modified while a status or feedback update is occurring.

Adding the synchronized() block should resolve the issue.  A proposed patch is attached.

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=31_

**Comment by chadrockey** [comment]
_From khug...@google.com on January 19, 2012 17:28:22_
This has been fixed and pushed.

I thought about using a copy-on-write list, but decided against.
