### ISSUE TITLE
Missing leading slash in service name leads to runtime exception on standard ROS Master

### ISSUE THREAD

**Issue by chadrockey** [rosjava/rosjava_core#66]
_Original author: martin.g...@gmail.com (October 14, 2011 19:19:57)_

When creating a service server and specifying the service name without a leading slash (&quot;add_two_ints&quot; instead of &quot;/add_two_ints&quot;), and then calling this service (either from rosjava or externally via a Python script), the following happens:
- on rosjava's ROS master, the service is uncallable (not found both with and without leading slash).
- on a standard ROS master, a runtime exception is thrown (see below).

<b>What steps will reproduce the problem?</b>
1. Create a new ServiceServer along the following lines:

private static final String SERVICE_NAME = &quot;add_two_ints&quot;;  // notice the missing leading slash
private static final String SERVICE_TYPE = &quot;test_ros/AddTwoInts&quot;;

ServiceServer&lt;AddTwoInts.Request, AddTwoInts.Response&gt; server =
    serverNode.newServiceServer(SERVICE_NAME, SERVICE_TYPE,
        new ServiceResponseBuilder&lt;AddTwoInts.Request, AddTwoInts.Response&gt;() {
          @Override
          public AddTwoInts.Response build(AddTwoInts.Request request) {
            AddTwoInts.Response response = new AddTwoInts.Response();
            response.sum = request.a + request.b;
            return response;
          }
        });
1. Run this node on a standard ROS Master (not the one from rosjava).
2. Call the service.

<b>What is the expected output? What do you see instead?</b>

Expected: either an error when creating the ServiceServer, or normal operation (leading slash added automatically).

Instead:
WARNING: An exception was thrown by a user handler while handling an exception event ([id: 0x005ff916, /127.0.0.1:50892 :&gt; /127.0.0.1:53533] EXCEPTION: java.lang.IllegalStateException)
org.ros.exception.RosRuntimeException: java.lang.IllegalStateException
    at org.ros.internal.transport.ConnectionTrackingHandler.exceptionCaught(ConnectionTrackingHandler.java:63)
    at org.jboss.netty.channel.Channels.fireExceptionCaught(Channels.java:432)
    at org.jboss.netty.channel.AbstractChannelSink.exceptionCaught(AbstractChannelSink.java:52)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:302)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:317)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:299)
    at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:216)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:274)
    at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:261)
    at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:349)
    at org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
    at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
Caused by: java.lang.IllegalStateException
    at com.google.common.base.Preconditions.checkState(Preconditions.java:129)
    at org.ros.internal.transport.tcp.TcpServerHandshakeHandler.messageReceived(TcpServerHandshakeHandler.java:67)
    ... 12 more

<b>What version of the product are you using? On what operating system?</b>

latest hg (791:9b22963f59ec), Ubuntu.

<b>Please provide any additional information below.</b>

_Original issue: http://code.google.com/p/rosjava/issues/detail?id=66_

**Comment by chadrockey** [comment]
_From damonkoh...@google.com on November 11, 2011 14:40:32_
This issue was closed by revision 9a706745e299.
